@endpoint=http://127.0.0.1:8080

### 어드민 로그인하기
POST {{endpoint}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "aaa@bbb.com",
    "password" : "1q2w3e4r"
}

### 사용자 로그인하기
POST {{endpoint}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "cruel32@nate.com",
    "password" : "1q2w3e4r"
}

### 프로필 가져오기 (토큰없이)
GET {{endpoint}}/api/profile HTTP/1.1


### 프로필 가져오기
GET {{endpoint}}/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInN1YiI6MSwibmFtZSI6IkFETUlOIiwiaWF0IjoxNjA4NjIyNzI3LCJleHAiOjE2MDkyMjc1Mjd9.TKPuHpPXELWiR8clkhnbh_Js8uWSe0nuXK1WD-Yu0tU

