@endpoint=http://127.0.0.1:3000

### 로그인하기
POST {{endpoint}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username" : "name1",
    "password" : "changeme"
}

### 프로필 가져오기 (토큰없이)
GET {{endpoint}}/profile HTTP/1.1


### 프로필 가져오기
GET {{endpoint}}/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hbWUiLCJzdWIiOjEsImlhdCI6MTYwNjk3MjIxNCwiZXhwIjoxNjA3NTc3MDE0fQ.ETshLHfM-b9XSKWaKs2u0I2hapsOoSj_lDbZ860oqb8

