@endpoint=http://127.0.0.1:8080

### shop 가져오기
GET {{endpoint}}/api/pudu/shop HTTP/1.1


### shop 가져오기
GET {{endpoint}}/api/pudu/shop?page=1&limit=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInN1YiI6MSwibmFtZSI6IkFETUlOIiwiaWF0IjoxNjA5NzQwOTA0LCJleHAiOjE2MTAzNDU3MDR9.iHPDujYMIx59dk8UJ6Zkwgk2WWuJjozuv3RJGvAJLFk
